modifyLineBreaks:
    # oneSentencePerLine:
    #     manipulateSentences: 1
    #     removeSentenceLineBreaks: 0
    #     sentencesFollow:
    #         par: 1
    #         blankLine: 1
    #         fullStop: 1
    #         exclamationMark: 1
    #         questionMark: 1
    #         rightBrace: 1
    #         commentOnPreviousLine: 1
    #         other: 0
    #     sentencesBeginWith:
    #         A-Z: 1
    #         a-z: 0
    #         other: 0
    #     sentencesEndWith:
    #         basicFullStop: 0
    #         betterFullStop: 0
    #         exclamationMark: 1
    #         questionMark: 1
    #         other: '(?:\.\)(?!\h*[a-z]))|(?:(?<!(?:(?:e\.g)|(?:i\.e)|(?:etc))))\.(?!(?:[a-z]|[A-Z]|\-|\,|\.|[0-9]))'
    textWrapOptions:
        columns: 120
        multipleSpacesToSingle: 1              
        removeBlockLineBreaks: 1
        when: before                        # before/after
