#!/usr/bin/zsh
export KITTY_DARK_THEME=Afterglow
export KITTY_LIGHT_THEME=Doom_One_Light
kitty @ set-colors --all /home/phuoc101/.config/kitty/Doom_One_Light.conf
sed -i '$s/'"$KITTY_DARK_THEME"'.conf/'"$KITTY_LIGHT_THEME"'.conf/' ~/.config/kitty/kitty.conf
gsettings set org.gnome.desktop.background picture-uri file:///home/phuoc101/Pictures/wallpapers/kate-hazen-unleash-your-robot-blue.png
kill -SIGUSR1 $(pgrep kitty) 
