#!/usr/bin/zsh
export DOTFILES_DIR=~/dotfiles
export KITTY_DARK_THEME=oxocarbon
export KITTY_LIGHT_THEME=Doom_One_Light
export NVIM_BG=dark
sed -i 's/'"$KITTY_LIGHT_THEME"'.conf/'"$KITTY_DARK_THEME"'.conf/' ~/.config/kitty/kitty.conf
kill -SIGUSR1 $(pgrep kitty)
sed -i 's/light/dark/' $DOTFILES_DIR/.config/alacritty/alacritty.yml
sed -i 's/colorscheme = "dayfox"/colorscheme = "carbonfox"/' $DOTFILES_DIR/.config/nvim/lua/plugins/colorscheme.lua
# gsettings set org.gnome.desktop.background picture-uri file:///home/phuoc101/Pictures/wallpapers/ds-dark.jpg
