#!/usr/bin/zsh
export DOTFILES_DIR=/media/phuoc101/imaunicorn/backup/linux_setups/dotfiles
export KITTY_DARK_THEME=One_Half_Dark
export KITTY_LIGHT_THEME=papercolor-light
export NVIM_BG=dark
sed -i 's/'"$KITTY_LIGHT_THEME"'.conf/'"$KITTY_DARK_THEME"'.conf/' ~/.config/kitty/kitty.conf
sed -i 's/light/dark/' $DOTFILES_DIR/alacritty/alacritty.yml
gsettings set org.gnome.desktop.background picture-uri file:///home/phuoc101/Pictures/wallpapers/ds-dark.jpg
kill -SIGUSR1 $(pgrep kitty)
