#! /usr/bin/bash

opt_all=false
opt_screen=false
opt_lock=false
opt_bg=false
opt_polybar=false
lock_file=""
while getopts "sl:abp" OPTION;
do
    case "$OPTION" in
        a)
            opt_all=true
            notify-send "INIT ALL"
            ;;
        l)
            opt_lock=true
            lock_file="$OPTARG"
            ;;
        s)
            opt_screen=true
            ;;
        b)
            opt_bg=true
            ;;
        p)
            opt_polybar=true
            ;;
        \?)
            echo "Invalid option -OPTARG" >&2
            exit 1
            ;;
    esac
done
#
# Init displays
if [ "$opt_screen" == true ] || [ "$opt_all"  == true ]
then
    notify-send "INIT SCREEN"
    init_displays
fi

# Update lockscreen
if [ $opt_lock == true ]
then
    if [ "$lock_file" = "" ]
    then
        MY_WALLS_DIR=~/dotfiles/wallpapers_dark/
        MY_LOCKSCREEN=$MY_WALLS_DIR$(ls -1 $MY_WALLS_DIR | shuf -n 1)
    else
        MY_LOCKSCREEN=$(realpath $lock_file)
    fi
    notify-send "INIT LOCKSCREEN"
    notify-send "Updating betterlockscreen" "$MY_LOCKSCREEN"
    betterlockscreen -u $MY_LOCKSCREEN --fx dimblur
    notify-send "betterlockscreen updated" "$MY_LOCKSCREEN"
fi

if [ "$opt_all" == true ] || [ "$opt_polybar" == true ]
then
    ~/.config/polybar/scripts/launch.sh
fi

# Start background apps
if [ "$opt_all" == true ] || [ "$opt_bg" == true ]
then
    notify-send "INIT BACKGROUND PROGRAMS"
    echo "all: $opt_all"
    sleep 1
    if ! [ -x "$(command -v kdeconnect-indicator)" ]
    then
        notify-send "KDE-Connect not found"
    else
        kdeconnect-indicator &
        notify-send "KDE Connect started" "Available: $(kdeconnect-cli -a --name-only)"
    fi
    # Start ALSA service (for sound)
    alsactl init &
    notify-send "ALSA initiated"
    # Launching background apps
    copyq &
    notify-send "CopyQ initiated"
    /usr/bin/syncthing serve --no-browser --logfile=default &
    notify-send "Syncthing initiated"
fi
