#! /usr/bin/bash

opt_all=false
opt_screen=false
opt_lock=false
opt_bg=false
opt_polybar=false
while getopts "slabp" OPTION;
do
    case "$OPTION" in
        a)
            opt_all=true
            notify-send "INIT ALL"
            ;;
        l)
            opt_lock=true
            ;;
        s)
            opt_screen=true
            ;;
        b)
            opt_bg=true
            ;;
        p)
            opt_polybar=true
            ;;
        \?)
            echo "Invalid option -OPTARG" >&2
            exit 1
            ;;
    esac
done

# Update lockscreen
if [ $opt_lock == true ]
then
    MY_WALLS_DIR=~/dotfiles/wallpapers_dark/
    MY_LOCKSCREEN=$MY_WALLS_DIR$(ls -1 $MY_WALLS_DIR | shuf -n 1)
    notify-send "INIT LOCKSCREEN"
    notify-send "Updating betterlockscreen" "$MY_LOCKSCREEN"
    betterlockscreen -u $MY_LOCKSCREEN --fx dimblur
    notify-send "betterlockscreen updated" "$MY_LOCKSCREEN"
fi

if [ "$opt_all" == true ] || [ "$opt_polybar" == true ]
then
    init_displays -p
fi
#
# Init displays
if [ "$opt_screen" == true ] || [ "$opt_all"  == true ]
then
    notify-send "INIT SCREEN"
    init_displays
fi

# Start background apps
if [ "$opt_all" == true ] || [ "$opt_bg" == true ]
then
    notify-send "INIT BACKGROUND PROGRAMS"
    echo "all: $opt_all"
    sleep 1
    # kdeconnect-indicator &
    # notify-send "KDE Connect started" "Available: $(kdeconnect-cli -a --name-only)"
    # Start ALSA service (for sound)
    alsactl init;
    notify-send "ALSA initiated"
    # Launching background apps
    copyq &
    notify-send "CopyQ initiated"
    /usr/bin/syncthing serve --no-browser --logfile=default &
    notify-send "Syncthing initiated"
fi
