#! /usr/bin/bash

# ---
# Options handling
mode="nord"
poly_init=false
while getopts "ldnp" OPTION; do
    case "$OPTION" in
        d)
            mode="dark"
            ;;
        l)
            mode="light"
            ;;
        n)
            mode="nord"
            ;;
        p)
            poly_init=true
            ;;
        \?)
            echo "Invalid option -OPTARG" >&2
            exit 1
            ;;
    esac
done

# ---
# Wallpapers setup
if [ "$mode" == "nord" ]; then
    notify-send "Set nord mode walls"
    MY_WALLS_DIR=$HOME/dotfiles/wallpapers_nord/
elif [ $mode == "dark" ]; then
    notify-send "Set dark mode walls"
    MY_WALLS_DIR=$HOME/dotfiles/wallpapers_dark/
else
    notify-send "Set light mode walls"
    MY_WALLS_DIR=$HOME/dotfiles/wallpapers_light/
fi

XRANDR_OUT=$(xrandr)
if [[ $XRANDR_OUT == *"DP-1-0.1 connected"* ]]; then
    umonitor --load trio_work
    notify-send "Initialized display" "trio_work"
    xrandr --output DP-1-0.1 --primary
    if [ "$poly_init" == true ]; then
        ~/.config/polybar/scripts/launch.sh
    fi
elif [[ $XRANDR_OUT == *"HDMI-1-0 connected"* ]]; then
    umonitor --load dual_hdmi_2k
    notify-send "Initialized display" "dual_hdmi_2k"
    xrandr --output HDMI-1-0 --primary
    if [ "$poly_init" == true ]; then
        ~/.config/polybar/scripts/launch.sh
    fi
elif [[ $XRANDR_OUT == *"DP-1-0 connected"* ]]; then
    # umonitor --load mobile
    umonitor --load dual_2k
    notify-send "Initialized display" "dual_2k"
    xrandr --output DP-1-0 --primary
    if [ "$poly_init" == true ]; then
        ~/.config/polybar/scripts/launch.sh
    fi
elif [[ $XRANDR_OUT == *"DisplayPort-1 connected"* ]]; then
    umonitor --load dual_2k
    notify-send "Initialized display" "dual_2k"
    xrandr --output DisplayPort-1 --primary
elif [[ $XRANDR_OUT == *"DisplayPort-2 connected"* ]]; then
    umonitor --load dual_2k
    notify-send "Initialized display" "dual_2k"
    xrandr --output DisplayPort-2 --primary
else
    umonitor --load mobile
    xrandr --output eDP --primary
    notify-send "Initialized display" "mobile"
    if [ "$poly_init" == true ]; then
        ~/.config/polybar/scripts/launch.sh
    fi
fi

init_wallpapers -f "$MY_WALLS_DIR"
