#!/usr/bin/zsh
export DOTFILES_DIR=~/dotfiles
sed -i 's/dark.conf/light.conf/' ~/.config/kitty/kitty.conf
kill -SIGUSR1 $(pgrep kitty) 
sed -i 's/dark/light/' $DOTFILES_DIR/.config/alacritty/alacritty.yml
sed -i 's/colorscheme carbonfox/colorscheme dayfox/' $DOTFILES_DIR/.config/nvim/init.lua
reload_nvim_theme -c dayfox

# Change zsh highlight
# trash ~/.zsh/zsh-highlight-config.zsh
# echo 'ZSH_HIGHLIGHT_STYLES[root]="bg=red"' >> ~/.zsh/zsh-highlight-config.zsh
# echo 'ZSH_HIGHLIGHT_STYLES[precommand]=fg=#48B9C7,bold' >> ~/.zsh/zsh-highlight-config.zsh
# echo 'ZSH_HIGHLIGHT_STYLES[arg0]=fg=#575279,bold' >> ~/.zsh/zsh-highlight-config.zsh
# echo 'ZSH_HIGHLIGHT_STYLES[comment]="none"' >> ~/.zsh/zsh-highlight-config.zsh

source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# ZSH_HIGHLIGHT_STYLES[root]="bg=red"
# ZSH_HIGHLIGHT_STYLES[precommand]=fg=#48B9C7,bold
# ZSH_HIGHLIGHT_STYLES[arg0]=fg=#575279,bold
# ZSH_HIGHLIGHT_STYLES[comment]="none"
# Gnome wallpapers
# gsettings set org.gnome.desktop.background picture-uri file:///home/phuoc101/Pictures/wallpapers/ds-light.jpg
