command_timeout = 100

format = """
$os\
$username\
$hostname\
$directory\
$docker_context\
$python\
$conda\
$custom\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character
"""

palette = 'nord'

[palettes.nord]
bg0 = '#2E3440'
bg1 = '#3B4252'
bg2 = '#434C5E'
bg3 = '#4C566A'
fg = '#D8DEE9'
blue1 = '#5e81ac'
blue2 = '#81a1c1'
blue3 = '#88c0d0'
turquoise = '#8fbcbb'
red = '#BF616A'
yellow = '#EBCB8B'
pink = '#b48ead'
orange = '#d08770'
green = '#A2BE8A'

[character]
success_symbol = "[](bold fg:green)"
error_symbol = "[](bold fg:red)"

[os]
format = '[$symbol]($style) '	
style = "bold turquoise"
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[username]
style_user = 'fg bold'
style_root = 'red bold'
format = '[$user]($style) '
disabled = false
show_always = false

[hostname]
ssh_symbol = " "
ssh_only = true
format = '[$ssh_symbol](bold blue)@[$hostname](bold red) '
disabled = false

[directory]
read_only = " 󰌾"
read_only_style = "red bold"
style = "blue2 bold"
home_symbol = "  ~"
format = '[$path]($style)[$read_only]($read_only_style) '

[cmd_duration]
style = 'green bold'
format = '[ $duration]($style) '

[conda]
symbol = " "
ignore_base = false
format = '[$symbol$environment]($style) '

[docker_context]
style = "blue1 bold"
symbol = " "
format = '[$symbol$context]($style) '
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile', 'compose.yaml', 'compose.yml']

[git_branch]
symbol = " "
style = "pink bold"
format = '[$symbol$branch]($style) '

[fossil_branch]
symbol = " "

[git_status]
style = "orange bold"
format = '([\[$all_status$ahead_behind\]]($style)) '

[git_commit]
style = "yellow bold"
tag_symbol = '  '
commit_hash_length = 4

[lua]
symbol = " "
format = '[$symbol($version)]($style) '

[memory_usage]
symbol = "󰍛 "
format = '$symbol[$ram( | $swap)]($style) '

[package]
symbol = "󰏗 "
format = '[$symbol$version]($style) '

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version}) (\($virtualenv\))]($style) '

[sudo]
format = '[as $symbol] '


[custom.ros]
style = "turquoise bold"
command = "echo '󱜙 '$ROS_DISTRO''"
when = '[[ -v ROS_DISTRO ]]'
format = '[$output]($style) '
