export PATH=$PATH:/home/phuoc101/bin:/opt/gradle/gradle-6.3/bin
export PATH=/usr/lib/ccache:$PATH
export PATH=/usr/lib/cuda-11.2/bin:$PATH
export EDITOR='nvim'
export VISUAL='nvim'
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/media/phuoc101/imaunicorn/Projects/robot_proj_2022/turtlebot3_ws/src/turtlebot3/turtlebot3_simulations/turtlebot3_gazebo/models
export STARSHIP_CONFIG=~/.config/starship/starship.toml
export GTK_IM_MODULE=ibus
export QT4_IM_MODULE=xim
export QT_IM_MODULE=xim
export XMODIFIERS=@im=ibus
export CPATH=/usr/lib/cuda-11.2/targets/x86_64-linux/include:$CPATH
export LD_LIBRARY_PATH=/usr/lib/cuda-11.2/targets/x86_64-linux/lib:/usr/lib/cuda-11.2/lib64:$LD_LIBRARY_PATH
