#!/bin/bash
COLOR_BRIGHTNESS='#e5c07b'
BRIGHTNESS_VALUE=`brightnessctl | grep -o "(.*" | tr -d "()"`
BRIGHTNESS_NR=${BRIGHTNESS_VALUE//%}

if [ $BRIGHTNESS_NR -lt 20 ]; then
	BRIGHTNESS_ICON="%{F$COLOR_BRIGHTNESS}󰃞%{F-}"
elif [ $BRIGHTNESS_NR -lt 50 ]; then
	BRIGHTNESS_ICON="%{F$COLOR_BRIGHTNESS}󰃟%{F-}"
elif [ $BRIGHTNESS_NR -lt 80 ]; then
	BRIGHTNESS_ICON="%{F$COLOR_BRIGHTNESS}󰃝%{F-}"
else
	BRIGHTNESS_ICON="%{F$COLOR_BRIGHTNESS}󰃠%{F-}"
fi

echo "$BRIGHTNESS_ICON $BRIGHTNESS_VALUE"
